name: Write__Adapt__
title: WriteAdapt - Pour ceux qui aime le contenu
org: Compagnie Mobile
author: Jean Desbiens
author_url: https://github.com/jeandesbiens
base_url: ''
ctx_path: ''

# append
interpolate: false 1
haml:
  :ugly: true

# append
asciidoctor:
  :safe: safe
  :attributes:
    sitename: WriteAdapt
    base_url: ''
    ctx_path: ''
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font

profiles:
  development:
    deploy:
      dummy:
  production:
    base_url: http://{username}.github.io/writeadapt-{username}
    ctx_path: /writeadapt-{username}
    asciidoctor:
      :attributes:
        base_url: http://{username}.github.io/writeadapt-{username}
        ctx_path: /writeadapt-{username}
        # imagesdir must be absolute to work around Atom feed bug
        imagesdir: http://{username}.github.io/writeadapt-{username}/images
    deploy:
      host: github_pages
      branch: gh-pages